# Use the official Python image as the base image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y redis-tools

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements-replication.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements-replication.txt

# Copy the replication app files into the container
COPY . /app/

# Run the replication app
CMD ["python", "replication.py"]