# Use the official Python image as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements-service.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements-service.txt

# Copy the Flask application code into the container
COPY . .

# Expose the port on which the Flask app will run
EXPOSE 5050

# Command to run the Flask application
CMD ["python", "bookstore_service.py"]